### ISSUE TITLE
Accept an optional Promise

### ISSUE THREAD

**Issue by bheiskell** [shimaore/superagent-as-promised#1]
Hello,

It would be useful if `superagent-as-promised` optionally accepted a Promise object during initialization, similar to [superagent-promise](https://github.com/lightsofapollo/superagent-promise).

My use case involves extending the promise prototype to include an additional method. `superagent-promise` doesn't work well for my use case, because I'm actually consuming superagent via [supertest](https://github.com/visionmedia/supertest) which doesn't provide a hook to replace the superagent library (and `superagent-promise` is simply a wrapper - it doesn't modify superagent's prototype).

I'm happy to create a patch, if you're open to the idea.

Thanks!

**Comment by shimaore** [comment]
I like the idea, do you have a preferred Promise lib you'd like me to add tests for?

**Comment by shimaore** [comment]
I ended up testing for the case you described, extending the Promise library.

**Comment by bheiskell** [comment]
Thanks @shimaore!
